function p_plan = pos_quadrotor_plan(v_0,a_0,v_peak)
%POS_QUADROTOR_PLAN
%    P_PLAN = POS_QUADROTOR_PLAN(V_0,A_0,V_PEAK)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Mar-2019 11:57:28

p_plan = a_0.*(1.1e1./1.92e2)+v_0.*(1.3e1./3.2e1)+v_peak.*(3.0./3.2e1);
