function p_peak = pos_quadrotor_peak(v_0,a_0,v_peak)
%POS_QUADROTOR_PEAK
%    P_PEAK = POS_QUADROTOR_PEAK(V_0,A_0,V_PEAK)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Mar-2019 11:57:28

p_peak = a_0./1.2e1+v_0./2.0+v_peak./2.0;
