function p_f = pos_quadrotor_final(v_0,a_0,v_peak)
%POS_QUADROTOR_FINAL
%    P_F = POS_QUADROTOR_FINAL(V_0,A_0,V_PEAK)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Mar-2019 11:57:28

p_f = a_0./1.2e1+v_0./2.0+v_peak.*(3.0./2.0);
