function dx = dyn_quadrotor_toStop(tdummy,in2,udummy)
%DYN_QUADROTOR_TOSTOP
%    DX = DYN_QUADROTOR_TOSTOP(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Mar-2019 11:57:28

t = in2(5,:);
v_peak = in2(4,:);
t2 = t.^2;
dx = [v_peak-t2.*v_peak.*(3.0./4.0)+(t.*t2.*v_peak)./4.0;0.0;0.0;0.0;1.0];
