function dx = dyn_quadrotor_toPeak(tdummy,in2,udummy)
%DYN_QUADROTOR_TOPEAK
%    DX = DYN_QUADROTOR_TOPEAK(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Mar-2019 11:57:28

a_0 = in2(3,:);
t = in2(5,:);
v_0 = in2(2,:);
v_peak = in2(4,:);
t2 = t.^2;
dx = [v_0+a_0.*t-t2.*(a_0.*2.0+v_0.*3.0-v_peak.*3.0)+t.*t2.*(a_0+v_0.*2.0-v_peak.*2.0);0.0;0.0;0.0;1.0];
